### ISSUE TITLE
multipe waves are drawn in the same area

### ISSUE THREAD

**Issue by harrydl** [DrEdwardPCB/python-taew#1]
multipe waves are drawn in the same area,does the author have any good solutions?

**Comment by harrydl** [comment]
hoping to get author's help above problem..

**Comment by DrEdwardPCB** [comment]
Thank you for using the library and raising the question. In the original paper it’s algorithm only able to find wave where peak and trough that fits the criteria must sits together consecutively.

As most Elliot wave lies inside the noise to prevent lose track of possible Elliott wave and able to detect multiple scales, it employed a modified version of searching that each point could seed for multiple wave, and whenever the criteria does not match, will stop the exploration of that Elliott wave and kill that instances.

For ways to mitigate.

From developer side, we could add a scoring function and clustering function to filter out some Elliott wave with poor quality and group those more or less the same to the same output. These will be implement in the later release(collaboration appreciated)

from user side, we suggest depends on use case, simple moving average of different time interval could be applied to filter out some unwanted wave
There are plenty of library that could do the job such as ta or ta-lib

Hope the above answer could provide some insight in using the library.

**Comment by harrydl** [comment]
Thank you for your help. Now i have some ideas about this problem,looking forward to the new version.
